use real release tags, release branch, and publish to pypi

diff --git a/.github/workflows/reusable-upload.yml b/.github/workflows/reusable-upload.yml
--- a/.github/workflows/reusable-upload.yml
+++ b/.github/workflows/reusable-upload.yml
@@ -147,8 +147,7 @@ jobs:
           docker tag "batfish/batfish:${TEST_TAG}" "batfish/batfish:latest"
           echo placeholder for pushing "batfish/batfish:${RELEASE_TAG}" and "batfish/batfish:latest"
           docker push "batfish/batfish:${RELEASE_TAG}"
-          # TODO uncomment this
-          #docker push "batfish/batfish:latest"
+          docker push "batfish/batfish:latest"
       - name: Upload Allinone image
         run: |
           TEST_TAG="${{ inputs.test_tag }}"
@@ -159,8 +158,7 @@ jobs:
           docker tag "batfish/allinone:${TEST_TAG}" "batfish/allinone:latest"
           echo placeholder for pushing "batfish/allinone:${RELEASE_TAG}" and "batfish/allinone:latest"
           docker push "batfish/allinone:${RELEASE_TAG}"
-          # TODO uncomment this
-          #docker push "batfish/allinone:latest"
+          docker push "batfish/allinone:latest"
   prod_whl_upload:
     if: inputs.queue_prod_release && inputs.BATFISH_GITHUB_BATFISH_REPO == 'batfish/batfish' && inputs.BATFISH_GITHUB_PYBATFISH_REPO == 'batfish/pybatfish'
     environment: Release Pybatfish
@@ -186,36 +184,34 @@ jobs:
           cd pybatfish
           sed -i.bak -e "s/^__version__ = .*$/__version__ = \"${{ inputs.bf_version }}\"/" pybatfish/__init__.py
           rm -f pybatfish/__init__.py.bak
-          # TODO update the branch name to release-
-          BRANCH_NAME="github-actions-test-${{ inputs.bf_version }}"
+          BRANCH_NAME="release-${{ inputs.bf_version }}"
           git checkout origin/master -b "$BRANCH_NAME"
           git config user.name "open-source-buildkitebot"
           git config user.email "open-source-buildkitebot@intentionet.com"
           git commit -am "Prepare for release ${{ inputs.bf_version }}: Updating version number"
           git push -u origin "$BRANCH_NAME"
-      # TODO run these steps to actually publish the artifact
-      # - name: Publish to PyPI
-      #   uses: pypa/gh-action-pypi-publish@release/v1
-      #   with:
-      #     password: ${{ secrets.PYBATFISH_PYPI_TOKEN }}
-      # - name: Set up Python
-      #   uses: actions/setup-python@v4
-      #   with:
-      #     python-version: 3.9
-      # - name: Verify uploaded artifact
-      #   run: |
-      #     MAX_RETRIES=3
-      #     COUNTER=0
-      #     while ! pip install pybatfish==${{ inputs.bf_version }}
-      #     do
-      #       if [ $COUNTER -gt $MAX_RETRIES ]; then
-      #         echo "Could not install Pybf"
-      #         exit 1
-      #       fi
-      #       sleep 5
-      #       ((COUNTER+=1))
-      #     done
-      #     echo "Pybf installed"
-      #     # Assume successful import means a working artifact
-      #     python -c "from pybatfish.client.session import Session"
-      #     echo "Pybf import was successful!"
+      - name: Publish to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          password: ${{ secrets.PYBATFISH_PYPI_TOKEN }}
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
+      - name: Verify uploaded artifact
+        run: |
+          MAX_RETRIES=3
+          COUNTER=0
+          while ! pip install pybatfish==${{ inputs.bf_version }}
+          do
+            if [ $COUNTER -gt $MAX_RETRIES ]; then
+              echo "Could not install Pybf"
+              exit 1
+            fi
+            sleep 5
+            ((COUNTER+=1))
+          done
+          echo "Pybf installed"
+          # Assume successful import means a working artifact
+          python -c "from pybatfish.client.session import Session"
+          echo "Pybf import was successful!"
